# Generated by Django 5.2.12 on 2026-03-18 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Бизнес-элемент',
                'verbose_name_plural': 'Бизнес-элементы',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='accounts_bu_slug_4ba025_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(help_text='Формат: объект.действие (например: product.view, order.edit)', max_length=100, verbose_name='Код разрешения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='accounts.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Правило доступа',
                'verbose_name_plural': 'Правила доступа',
                'ordering': ['role', 'permission_code'],
                'indexes': [models.Index(fields=['permission_code'], name='accounts_ac_permiss_7bb152_idx')],
                'unique_together': {('role', 'permission_code')},
            },
        ),
    ]
