# Generated by Django 5.2.12 on 2026-03-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category_order_product_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='created_at',
        ),
    ]
