# Generated by Django 5.2.12 on 2026-03-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_role_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_email_5ce40b_idx',
            old_name='accounts_us_email_74c8d6_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_usernam_ab560e_idx',
            old_name='accounts_us_usernam_c0ea66_idx',
        ),
    ]
